"""
Read from dpocket log generated by:
load_dtm_file.py

"""

import sys
import numpy as np
import matplotlib.pyplot as plt


class dp_log():
    def __init__(self, *args):
        self.fluctuation, self.space, self.space_std, self.occupancy, self.occurrence, self.total_snapshot = args

    @property
    def stability(self):
        return self.occurrence / self.total_snapshot


def parser(lines):
    data = []

    for line in lines:
        fluctuation, space, space_std, occupancy, occurrence, total_snapshot = map(float, line.split())
        data.append(dp_log(fluctuation, space, space_std, occupancy, occurrence, total_snapshot))

    return data


def plot_occupancy_stability(lines):
    # data = [dp for dp in parser(lines) if dp.stability > 0.4]
    ## Screen all dpockets less than 40%

    data = parser(lines)
    data = data[:int(len(data) / 10)]

    ## first 10 percent

    data.sort(key=lambda a: a.stability,reverse=True)

    fig = plt.figure()
    ax = fig.gca()

    xs = np.arange(len(data))

    y1 = np.array([d.occupancy for d in data])
    y2 = np.array([d.stability for d in data])

    ax.bar(xs, y1)
    ax.plot(xs, y2)

    plt.xlabel("D-pocket index")

    plt.ylabel("occupancy/ stability")

    plt.title("occupancy(line) cs stability(bar)")

    plt.xticks(xs,rotation='vertical')

    plt.show()


if __name__ == '__main__':
    logfile = sys.argv[1]
    with open(logfile, 'r') as handle:
        lines = handle.readlines()[1:]
    plot_occupancy_stability(lines)
